### ISSUE TITLE
mipt value in TC data format is not initialized

### ISSUE THREAD

**Issue by cerminar** [PFCal-dev/cmssw#229]
Hello,

by chance I just realized that the value of the member variable:

`double mipPt_;`
in 
https://github.com/PFCal-dev/cmssw/blob/hgc-tpg-devel-CMSSW_10_3_0_pre4/DataFormats/L1THGCal/interface/HGCalTriggerCell.h#L56

is never initialized.
https://github.com/PFCal-dev/cmssw/blob/hgc-tpg-devel-CMSSW_10_3_0_pre4/DataFormats/L1THGCal/src/HGCalTriggerCell.cc

I think this is quite dangerous and, unless intentional, should be addressed.
Cheers,
G

**Comment by jbsauvan** [comment]
Right, thanks for spotting. I will provide a fix.

**Comment by jbsauvan** [comment]
It has been fixed in #228
