### ISSUE TITLE
Adding H/E to the multicluster datamembers?

### ISSUE THREAD

**Issue by gpetruc** [PFCal-dev/cmssw#261]
Hi,

I was wondering if you have objections at adding hOverE as a new Multicluster datamember (it's only useful for 3D clusters, not 2D ones).

Currently there's the function that computes it on the fly from the constituents, but it requires them to be in the event content (increasing file size) and especially since it has to read all that information it's *slow* (currently the largest time consumer in running the L1 PF algo).

I can make the PR if you want,

Giovanni

**Comment by jbsauvan** [comment]
Hi Giovanni, 

No problem.
If the H/E member is not filled, the computation from constituents should still be called as backup, to be sure that the behaviour stays the same for older objects.

Thanks!
