### ISSUE TITLE
Cluster variables for front-end and cluster studies

### ISSUE THREAD

**Issue by jbsauvan** [PFCal-dev/cmssw#296]
Trigger cell information will not be included in ntuples for the study of multiple front-end scenarios and clustering flavours, for size reasons.
Additional variables for 3D clusters may be useful to perform all the needed studies.
This issue is meant to build a comprehensive list of possible additional variables that could be implemented.

* Variables needed for cluster calibration and energy corrections
  - Cluster energies in each layer (38 float values). Could add a flag to switch on/off these branches.
* Variables needed for e/g shape and identification studies
  - Had and Em energies (Only Had value needed since we already have the total)
  - Number of layers
  - Last layer
  - Longitudinal percentiles (e.g. 10% and 90%). Would be similar to first and last layer but less sensitive to low energy layers
  - Core-constrained and full width variables (see, spp, srr, szz). Can remove the existing `max` and `mean` versions which are not useful anymore
  - z barycenter
  - Compactness? e.g. number of TCs containing X% of the total cluster energy
* Variables for jet studies

**Comment by jbsauvan** [comment]
@snwebb  @jbueghly @cerminar if you have any request/idea of new cluster variables to be implemented and included in our ntuples, please use this issue

**Comment by jbueghly** [comment]
I'm not sure if this belongs in this issue, but it might be useful to save sim clusters as well, to have a baseline that is independent of noise, pileup, etc. Those clusters would be formed only using the sim energy of the relevant trigger cells. Do others agree that this would be useful?

On the point of saving trigger cells: For front-end algorithm studies, saving trigger cells and their sim energy content could be very useful. It allows for performance comparisons that are independent of the backend (clustering). To mitigate the size issue, it might be possible to use a gen matching selector, like what I have currently implemented to select clusters. Is this something we could consider?

**Comment by jbsauvan** [comment]
> I'm not sure if this belongs in this issue, but it might be useful to save sim clusters as well, to have a baseline that is independent of noise, pileup, etc. Those clusters would be formed only using the sim energy of the relevant trigger cells. Do others agree that this would be useful?

Yes, certainly. Gianluca told me this week someone is working on that at CERN, and the implementation is already well advanced.
 
> On the point of saving trigger cells: For front-end algorithm studies, saving trigger cells and their sim energy content could be very useful. It allows for performance comparisons that are independent of the backend (clustering). To mitigate the size issue, it might be possible to use a gen matching selector, like what I have currently implemented to select clusters. Is this something we could consider?

Selectors will certainly be very useful. But in my opinion I would only save trigger cells once we have reduced the phase space a bit, after looking at existing 3D clusters.
