### ISSUE TITLE
SuperTC issues

### ISSUE THREAD

**Issue by jbsauvan** [PFCal-dev/cmssw#300]
* Sensitivity to noise
  - Could add noise threshold on TC before forming STC
  - Clustering threshold (#299) would also help removing propagation of noise to the clusters
* [x] Implementation of more flavours of SuperTC
* [x] Implementation of SuperTCs in the Scintillator section
  - Would it make sense to have a first simple implementation with 2x2 grouping?
* [x] Choice of a baseline size
  - 2x2 at high eta for 100um sensors and 3x3 for 200,300um sensors?
* [x] Add floating point compression of SuperTCs

**Comment by jbueghly** [comment]
I think it would be useful to save sim energy for super trigger cells. Currently, only the sim energy of the max energy trigger cell is saved, but really we are interested in the sum of sim energy in the four constituent trigger cells. Let me know whether you think we can implement this.

**Comment by jbsauvan** [comment]
It would require to be able to retrieve the list of TCs from a SuperTC using the geometry, which is not yet implemented. I let @snwebb comment if it something he planed to implement (which I think would also be needed for more general CoarseTC implementations).

**Comment by snwebb** [comment]
Yes I have a basic implementation of this and am I currently validating it. If all goes to plan I might make a pull request today.

**Comment by jbueghly** [comment]
I mentioned it in another issue, but I think it would be useful to allow combinations of thresholds and super-tcs.

**Comment by snwebb** [comment]
For the floating point compression of SuperTCs
- I guess the implementation will be very similar (if not exactly the same) to HGCalVFECompressionImpl.cc. Do you think it is possible or best practise to use exactly the same code, or is it better to copy it to a new class in the concentrator?

**Comment by jbsauvan** [comment]
I agree it's probably better to use the same code.

**Comment by snwebb** [comment]
Thanks - what is the input value that would be compressed in the case of the STCs - the hwPt?

**Comment by jbsauvan** [comment]
The TC `hwPt` is containing the compressed charge put on the original linear scale [1]. So what could be done is to sum the TCs `hwPt`, apply the floating point compression on the summed values, and finally recompute the mipT and calibrated values on the STC compressed `hwPt` summed values [2].

[1] https://github.com/PFCal-dev/cmssw/blob/hgc-tpg-devel-CMSSW_11_0_0_pre2/L1Trigger/L1THGCal/plugins/veryfrontend/HGCalVFEProcessorSums.cc#L48
https://github.com/PFCal-dev/cmssw/blob/hgc-tpg-devel-CMSSW_11_0_0_pre2/L1Trigger/L1THGCal/src/veryfrontend/HGCalVFECompressionImpl.cc#L72
[2] https://github.com/PFCal-dev/cmssw/blob/hgc-tpg-devel-CMSSW_11_0_0_pre2/L1Trigger/L1THGCal/src/veryfrontend/HGCalTriggerCellCalibration.cc#L73
