### ISSUE TITLE
HGCalTriggerChains broken in development branch?

### ISSUE THREAD

**Issue by cerminar** [PFCal-dev/cmssw#313]
Hello, 

it looks like in the current development branch the `HGCalTriggerChains` are broken because of [Line](https://github.com/PFCal-dev/cmssw/blob/hgc-tpg-devel-CMSSW_10_6_0_pre2/L1Trigger/L1THGCalUtilities/python/hgcalTriggerChains.py#L100)

which results in:
LookupError: process has no item of label hgcalTriggerSelector

The other option is that I didn't get how to use it...but I don't think I really need a selector.
:)

Thanks for your help,
G

**Comment by jbsauvan** [comment]
Thanks. I'll fix it.

**Comment by jbsauvan** [comment]
#315 should do the trick.
You can also add this line in your cfg file, even if you're not using it:
```python
process.load('L1Trigger.L1THGCalUtilities.HGC3DClusterGenMatchSelector_cff')
```

**Comment by jbsauvan** [comment]
Now in release 3.6.8
