### ISSUE TITLE
Splitting seeding and clustering parameters

### ISSUE THREAD

**Issue by jbsauvan** [PFCal-dev/cmssw#320]
Seeding and clustering should be made independent in their parametrization. Currently there is a single PSet for both of them and the customizations are often a combination of seeding and clustering customizations (e.g. `custom_3dclustering_histoMax_variableDr`).

- Two independent PSets should be created for seeding and clustering
- Customization functions should be independent to be able to configure easily combinations of seeding and clustering.

**Comment by snwebb** [comment]
Yes, i'll do this (after Easter)

**Comment by snwebb** [comment]
Is this something we would still like/need? If so I'll work on it.

**Comment by jbsauvan** [comment]
Yes, given that the set of possible seeding and clustering options is likely to grow in the future, it will be needed to facilitate their configuration.
Thanks!
