### ISSUE TITLE
Wafer info in TC ntuples

### ISSUE THREAD

**Issue by cerminar** [PFCal-dev/cmssw#366]
It looks like the wafer information is currently not handled consistently in the `HGCalTriggerNtupleHGCTriggerCells`.
The `wafer` branch is declared but not filled  for the V9 detids while the `waferu` and `waferv`containers are filled but not associated to any branch.  

https://github.com/PFCal-dev/cmssw/blob/38134abd08e302f4e76e7cd78b70e852abf7196c/L1Trigger/L1THGCalUtilities/plugins/ntuples/HGCalTriggerNtupleHGCTriggerCells.cc#L131

**Comment by jbsauvan** [comment]
Thanks, right, this is something which had been removed accidentally in one PR. I applied a fix locally for occupancy studies I did, but didn't push it.
I'll propagate the fix.

**Comment by cerminar** [comment]
Thanks @jbsauvan !
The same is true for `cell`

**Comment by jbsauvan** [comment]
Concerning the `wafer` vs `waferu, waferv` declarations, currently we need to declare all branches because we can have V8 detids with the V9 geometry and there is no way to know this in the initialization.

**Comment by jbsauvan** [comment]
The fix has been merged in the devel branch (now based on 11_0_0_pre2) and release 3.10.3 has been created (based on 10_6_0)
