### ISSUE TITLE
Implement a TriggerCell data format

### ISSUE THREAD

**Issue by jbsauvan** [PFCal-dev/cmssw#45]
- It should include information like energy, detid, etc.
- FE Codec should be able to decode front-end digis into a vector of such TriggerCell, such that backend algorithms can easily use them, after decoding.

**Comment by lgray** [comment]
OK - basically RecHits for trigger? I imagine with some notion of LSB and other fixed-width math considerations?

Don't think it would be too hard to do this. I can give a try the end of the week/beginning of next.

**Comment by jbsauvan** [comment]
Thanks @lgray 
Yes, something like that.

Someone volunteered to implement that before summer, but I haven't heard from him for a long time. I'll ping him again; If I get no response then you can implement it if you have time.
