### ISSUE TITLE
Trigger DetID

### ISSUE THREAD

**Issue by amarini** [PFCal-dev/cmssw#5]
- define a trigger detid

**Comment by amarini** [comment]
I started to look into the detIds and the cleanest way is to use the already existing infrastructure.
We can use the HGCalDetId defining a new "subdetector" (HGCTrigger, [here](https://github.com/PFCal-dev/cmssw/blob/hgc_trigger_fwk_SLHC26p3/DataFormats/ForwardDetId/interface/ForwardSubdetector.h) )

[HGCalDetId.h](https://github.com/PFCal-dev/cmssw/blob/hgc_trigger_fwk_SLHC26p3/DataFormats/ForwardDetId/interface/HGCalDetId.h)

@lgray, do you know why there are defined some [HGCalEE](https://github.com/PFCal-dev/cmssw/blob/hgc_trigger_fwk_SLHC26p3/DataFormats/ForwardDetId/interface/HGCEEDetId.h) and [HGCalHE](https://github.com/PFCal-dev/cmssw/blob/hgc_trigger_fwk_SLHC26p3/DataFormats/ForwardDetId/interface/HGCHEDetId.h), with sligthly different bit-mask? If I look carefully, all these implementation change some of the global interface definitions [here, DetId.h](https://github.com/PFCal-dev/cmssw/blob/hgc_trigger_fwk_SLHC26p3/DataFormats/DetId/interface/DetId.h#L11-L15), but they are unlikely to be handled correctly by the parent class.

Then looking into @jbsauvan code, we just need to change the instantiation [here](https://github.com/PFCal-dev/cmssw/blob/hgc_trigger_fwk_SLHC26p3/L1Trigger/L1THGCal/plugins/geometries/HGCalTriggerGeometryImp1.cc#L92) to have the subdetector that we want. (I would use the subsector for the module number, and for the module a invalid cell number, eg 0xFFFF)

**Comment by lgray** [comment]
@amarini The HGCalDetId is for simulation/Geant. The HGCalE and HGCalHE det ids are for the reco geometry. I think it might be best just to make HGCalTriggerDetId
