### ISSUE TITLE
Implement threshold before trigger cell sums

### ISSUE THREAD

**Issue by jbsauvan** [PFCal-dev/cmssw#74]
In order to avoid propagating noise to trigger cells, which potentially would degrade resolution. 
To be implemented to check the impact.

**Comment by jbueghly** [comment]
Has there been any recent progress on this issue? The noise has a substantial impact on our shower shape studies, especially for super trigger cells. There are ways to get around this with trigger cell thresholds and clustering thresholds, but handling it in the very front end would be a better solution. I can also help with this if you'd like.

**Comment by jbsauvan** [comment]
I just implemented it. I'm checking things before making the PR.

**Comment by jbsauvan** [comment]
Implemented in #308
